from django.urls import path

from .views import (
    AdminAiGenerationsView,
    AdminAiPresetDetailView,
    AdminAiPresetTestView,
    AdminAiPresetsView,
    AdminAnalyticsExportView,
    AdminDashboardView,
    AdminEventDetailView,
    AdminEventsView,
    AdminInvitationsView,
    AdminMoodTagDetailView,
    AdminMoodTagsView,
    AdminSystemLogsView,
    AdminTemplateDetailView,
    AdminTemplateTestView,
    AdminTemplatesView,
    AdminTextTemplateDetailView,
    AdminTextTemplatesView,
    AdminUserDetailView,
    AdminUsersView,
)

urlpatterns = [
    path("admin/dashboard", AdminDashboardView.as_view()),
    path("admin/users", AdminUsersView.as_view()),
    path("admin/users/<uuid:pk>", AdminUserDetailView.as_view()),
    path("admin/events", AdminEventsView.as_view()),
    path("admin/events/<uuid:pk>", AdminEventDetailView.as_view()),
    path("admin/text-templates", AdminTextTemplatesView.as_view()),
    path("admin/text-templates/<uuid:pk>", AdminTextTemplateDetailView.as_view()),
    path("admin/templates", AdminTemplatesView.as_view()),
    path("admin/templates/<uuid:pk>", AdminTemplateDetailView.as_view()),
    path("admin/templates/<uuid:pk>/test", AdminTemplateTestView.as_view()),
    path("admin/mood-tags", AdminMoodTagsView.as_view()),
    path("admin/mood-tags/<uuid:pk>", AdminMoodTagDetailView.as_view()),
    path("admin/ai-presets", AdminAiPresetsView.as_view()),
    path("admin/ai-presets/<uuid:pk>", AdminAiPresetDetailView.as_view()),
    path("admin/ai-presets/<uuid:pk>/test", AdminAiPresetTestView.as_view()),
    path("admin/invitations", AdminInvitationsView.as_view()),
    path("admin/ai-generations", AdminAiGenerationsView.as_view()),
    path("admin/system-logs", AdminSystemLogsView.as_view()),
    path("admin/analytics/export", AdminAnalyticsExportView.as_view()),
]
