# Generated by Django 5.2.16 on 2026-07-15 04:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=64)),
                ('event_name', models.CharField(max_length=64)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('utm_source', models.CharField(blank=True, max_length=64, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=64, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=64, null=True)),
                ('referrer_url', models.URLField(blank=True, max_length=512, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('new_users', models.IntegerField(default=0)),
                ('dau', models.IntegerField(default=0)),
                ('invitations_created', models.IntegerField(default=0)),
                ('invitations_completed', models.IntegerField(default=0)),
                ('ai_generations_count', models.IntegerField(default=0)),
                ('ai_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('downloads_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('subtype_slug', models.CharField(blank=True, max_length=32, null=True)),
                ('inviter_type', models.CharField(blank=True, max_length=32, null=True)),
                ('language', models.CharField(choices=[('uz-cyrl', 'Uzbek Cyrillic'), ('uz-latn', 'Uzbek Latin'), ('ru', 'Russian')], default='uz-cyrl', max_length=16)),
                ('event_data', models.JSONField(default=dict)),
                ('generation_path', models.CharField(blank=True, choices=[('template', 'Template'), ('ai_from_scratch', 'AI from scratch')], max_length=32, null=True)),
                ('selected_mood_tags', models.JSONField(blank=True, default=list)),
                ('custom_style_note', models.TextField(blank=True, null=True)),
                ('primary_format', models.CharField(default='4:5', max_length=8)),
                ('final_image_url', models.URLField(blank=True, max_length=512, null=True)),
                ('additional_formats', models.JSONField(blank=True, default=dict, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('generation_count', models.IntegerField(default=0)),
                ('last_generation_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('last_job_id', models.CharField(blank=True, max_length=64, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationHistory',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('welcome', 'Welcome'), ('generation_complete', 'Generation complete'), ('expiring_soon', 'Expiring soon'), ('seasonal', 'Seasonal')], max_length=32)),
                ('channel', models.CharField(choices=[('telegram_bot', 'Telegram bot'), ('in_app', 'In-app')], default='telegram_bot', max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('language', models.CharField(choices=[('uz-cyrl', 'Uzbek Cyrillic'), ('uz-latn', 'Uzbek Latin'), ('ru', 'Russian')], max_length=16)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RenderedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file_type', models.CharField(choices=[('hd_4_5', '4:5'), ('hd_9_16', '9:16'), ('hd_1_1', '1:1')], max_length=16)),
                ('url', models.URLField(max_length=512)),
                ('cdn_url', models.URLField(max_length=512)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShareEvent',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('copy_link', 'Copy link'), ('other', 'Other')], max_length=32)),
                ('clicked_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('resulted_in_signup', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
