# Generated by Django 5.2.16 on 2026-07-16 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='subtype_slugs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='invitationhistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
