# Generated by Django 5.2.16 on 2026-09-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_default_language_uz_latn'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRateLimit',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('per_hour', models.PositiveIntegerField(default=20)),
                ('per_day', models.PositiveIntegerField(default=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Generation rate limit',
                'verbose_name_plural': 'Generation rate limits',
            },
        ),
    ]
