# Generated by Django 5.2.17 on 2026-09-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0005_generation_rate_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
