# Generated by Django 5.2.16 on 2026-08-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('uz-latn', 'Uzbek Latin'), ('uz-cyrl', 'Uzbek Cyrillic'), ('ru', 'Russian')], default='uz-latn', max_length=16),
        ),
    ]
