# Generated by Django 5.2.16 on 2026-09-09 08:38

from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Coalesce


def backfill_last_seen(apps, schema_editor):
    User = apps.get_model("users", "User")
    # Prefer custom last_login_at, then Django last_login.
    User.objects.filter(last_seen_at__isnull=True).update(
        last_seen_at=Coalesce(F("last_login_at"), F("last_login"))
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_default_language_uz_latn"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["last_seen_at"], name="users_user_last_se_8aae7b_idx"),
        ),
        migrations.RunPython(backfill_last_seen, migrations.RunPython.noop),
    ]
