# Generated by Django 5.2.16 on 2026-07-15 04:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('icon_url', models.URLField(blank=True, max_length=512, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name_translations', models.JSONField(default=dict)),
                ('description_translations', models.JSONField(blank=True, default=dict, null=True)),
                ('subtypes', models.JSONField(blank=True, default=list, null=True)),
                ('fields_schema', models.JSONField(default=dict)),
                ('color_themes', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='MoodTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('category', models.CharField(choices=[('color', 'Color'), ('flowers', 'Flowers'), ('style', 'Style'), ('texture', 'Texture')], max_length=16)),
                ('name_translations', models.JSONField(default=dict)),
                ('prompt_snippet', models.CharField(max_length=256)),
                ('icon_url', models.URLField(blank=True, max_length=512, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtype_slug', models.CharField(blank=True, max_length=32, null=True)),
                ('theme_name', models.CharField(max_length=128)),
                ('style_tags', models.JSONField(blank=True, default=list)),
                ('color_palette', models.JSONField(blank=True, default=list)),
                ('mood_tags', models.JSONField(blank=True, default=list)),
                ('bg_url', models.URLField(max_length=512)),
                ('bg_url_preview', models.URLField(max_length=512)),
                ('ai_composition_prompt', models.TextField()),
                ('supports_dark_text', models.BooleanField(default=True)),
                ('dominant_colors', models.JSONField(blank=True, default=list)),
                ('supported_formats', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtype_slug', models.CharField(blank=True, max_length=32, null=True)),
                ('inviter_type', models.CharField(blank=True, max_length=32, null=True)),
                ('language', models.CharField(choices=[('uz-cyrl', 'Uzbek Cyrillic'), ('uz-latn', 'Uzbek Latin'), ('ru', 'Russian')], max_length=16)),
                ('title', models.CharField(max_length=128)),
                ('preview_text', models.TextField()),
                ('variables_used', models.JSONField(default=list)),
                ('tone', models.CharField(blank=True, choices=[('classic', 'Classic'), ('warm', 'Warm'), ('formal', 'Formal'), ('poetic', 'Poetic'), ('modern', 'Modern')], max_length=16, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIPromptPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('base_prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True, null=True)),
                ('model_params', models.JSONField(default=dict)),
                ('example_output_url', models.URLField(blank=True, max_length=512, null=True)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(blank=True, db_column='event_slug', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_presets', to='content.eventconfig', to_field='slug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
