# Generated by Django 5.2.16 on 2026-07-15 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='created_by_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template',
            name='event',
            field=models.ForeignKey(db_column='event_slug', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='content.eventconfig', to_field='slug'),
        ),
        migrations.AddField(
            model_name='texttemplate',
            name='created_by_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_text_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='texttemplate',
            name='event',
            field=models.ForeignKey(db_column='event_slug', on_delete=django.db.models.deletion.CASCADE, related_name='text_templates', to='content.eventconfig', to_field='slug'),
        ),
        migrations.AddIndex(
            model_name='texttemplate',
            index=models.Index(fields=['event', 'language', 'is_active'], name='content_tex_event_s_36da0d_idx'),
        ),
        migrations.AddIndex(
            model_name='texttemplate',
            index=models.Index(fields=['-usage_count'], name='content_tex_usage_c_f9dd1d_idx'),
        ),
    ]
