# Generated by Django 5.2.16 on 2026-09-14 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='texttemplate',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_text_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='texttemplate',
            name='language',
            field=models.CharField(choices=[('uz-latn', 'Uzbek Latin'), ('uz-cyrl', 'Uzbek Cyrillic'), ('ru', 'Russian')], max_length=16),
        ),
    ]
