# Generated by Django 5.2.16 on 2026-09-15 04:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('main_text', models.TextField(blank=True, default='')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=240)),
                ('design_config', models.JSONField(blank=True, default=dict)),
                ('music_config', models.JSONField(blank=True, default=dict)),
                ('design_prompt', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('unpublished', 'Unpublished')], default='draft', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='page_builde_user_id_c3de90_idx'), models.Index(fields=['status'], name='page_builde_status_19d6ae_idx')],
            },
        ),
    ]
