# Generated by Django 5.2.16 on 2026-07-15 04:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=64, null=True)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(default='gemini-2.5-flash-image', max_length=64)),
                ('generation_path', models.CharField(choices=[('template', 'Template'), ('ai_from_scratch', 'AI from scratch')], max_length=32)),
                ('base_image_url', models.URLField(blank=True, max_length=512, null=True)),
                ('final_prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True, null=True)),
                ('model_params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='queued', max_length=16)),
                ('result_url', models.URLField(blank=True, max_length=512, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('provider_cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIGenerationCache',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('cache_key', models.CharField(max_length=128, unique=True)),
                ('generation_path', models.CharField(choices=[('template', 'Template'), ('ai_from_scratch', 'AI from scratch')], max_length=32)),
                ('result_url', models.URLField(max_length=512)),
                ('hit_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=16)),
                ('module', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
