# Generated by Django 5.2.17 on 2026-09-23 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitations', '0006_invitation_is_paid_invitation_paid_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paycom_transaction_id', models.CharField(max_length=32, unique=True)),
                ('paycom_time', models.BigIntegerField()),
                ('amount', models.BigIntegerField(help_text="Amount in tiyin (1 so'm = 100 tiyin)")),
                ('state', models.SmallIntegerField(choices=[(1, 'Created'), (2, 'Completed'), (-1, 'Cancelled'), (-2, 'Cancelled after complete')], default=1)),
                ('reason', models.SmallIntegerField(blank=True, null=True)),
                ('create_time', models.BigIntegerField()),
                ('perform_time', models.BigIntegerField(default=0)),
                ('cancel_time', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payme_transactions', to='invitations.invitation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invitation'], name='payments_pa_invitat_8dffce_idx'), models.Index(fields=['state'], name='payments_pa_state_1a0ad5_idx')],
            },
        ),
    ]
